### ISSUE TITLE
您好，我想问一下关于init函数里的问题

### ISSUE THREAD

**Issue by LTstrange** [dengyaolong/2048python#1]
程序里的init（）函数中，mtr[ran_pos[0]/4][ran_pos[0]%4]这条语句中的ran_pos[0]/4是一个float吧？我这里运行的时候报错了，这里不太明白，望解答，谢谢Ծ ̮ Ծ

**Comment by dengyaolong** [comment]
@LTstrange 使用python2.7即可。python3会处理成浮点，而2.7会直接处理成整型。我当时用的就是2.7。

**Comment by LTstrange** [comment]
谢谢(◔◡◔)
